### ISSUE TITLE
[Install] Add Debian package and PPA

### ISSUE THREAD

**Issue by vsergeev** [vsergeev/luaradio#12]
Add Debian package and PPA for x86 and ARM.

**Comment by F5OEO** [comment]
Or at least a HowTo install on Debian Jessie for raspberry pi users. Thanks :)

**Comment by vsergeev** [comment]
In the meanwhile, you can install `luajit` from the package repositories, and `libvolk0.0.0` from the package repositories and/or [liquid-dsp](https://github.com/jgaeddert/liquid-dsp) from source.

That should let you run LuaRadio from the repo with acceleration and its examples. Double check that `./luaradio --platform` shows `volk` and/or `liquid` marked as try. You can also install LuaRadio more permanently if you'd like, with the install from the source instructions.

**Comment by F5OEO** [comment]
Ok, under Raspbian Jessie :
sudo apt-get install libluajit-5.1-dev
sudo apt-get install fftw3-dev
and install liquid-dsp from git

Have to give a try with luaradio modulation and
https://github.com/F5OEO/rpitx

2016-07-03 20:43 GMT+02:00 Vanya Sergeev <notifications@github.com>:
