### ISSUE TITLE
[OS X] Fix Mac OS X installation paths

### ISSUE THREAD

**Issue by gyaresu** [vsergeev/luaradio#21]
Permissions issues trying to install it on OSX 10.11.5

```
zaphod➜  embed : master ✔ : ᐅ  sudo make install
install -d /usr/lib
install: chmod 755 /usr/lib: Operation not permitted
install -m755 build/libluaradio.a /usr/lib/libluaradio.a
install: /usr/lib/libluaradio.a: Operation not permitted
make: *** [install] Error 71
```

**Comment by vsergeev** [comment]
This OS X install process in the Makefile is going to get cleaned up, both for this and a few things mentioned in the homebrew [PR](https://github.com/Homebrew/homebrew-core/pull/2665).
