### ISSUE TITLE
[Block] Add SoapySDR vendor-neutral SDR source block

### ISSUE THREAD

**Issue by rxseger** [vsergeev/luaradio#28]
A source (and/or sink) block for https://github.com/pothosware/SoapySDR would add support for most SDR device types automatically, without the need for vendor-specific blocks like:

https://github.com/vsergeev/luaradio/issues/20 SDRplay
https://github.com/vsergeev/luaradio/issues/19 bladeRF
https://github.com/vsergeev/luaradio/issues/18 HackRF
https://github.com/vsergeev/luaradio/issues/11 AirSpy
RtlSdrSource

**Comment by vsergeev** [comment]
SoapySDRSource and SoapySDRSink blocks will certainly be added to LuaRadio. In some cases, they appear to be the best way to support certain hardware SDRs (e.g. LimeSDR).

The vendor-specific blocks will probably also remain, though, so as not to strictly require the install of a middleware like SoapySDR and its individual plugins, in addition to the underlying libraries.
