### ISSUE TITLE
[Block] Precisify the percentage remaining to feature-parity with GNU Radio's blocks

### ISSUE THREAD

**Issue by rht** [vsergeev/luaradio#38]
For the latter, the list could be found in http://gnuradio.org/redmine/projects/gnuradio/wiki/FAQ#Where-can-I-find-a-list-of-GNU-Radio-blocks.

(while it is much harder to keep track of supported hw frontend)

**Comment by vsergeev** [comment]
Archiving for now -- may revisit this later.
