### ISSUE TITLE
[OS X] Running `luaradio` crashes on startup, symbol in `libSoapySDR` not found.

### ISSUE THREAD

**Issue by ralfbiedert** [vsergeev/luaradio#44]
# Overview

Running the latest `luaradio` on 10.12.6 crashes on startup with:

```
dyld: lazy symbol binding failed: Symbol not found: __Z10getEnvImplPKc
  Referenced from: libSoapySDR.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z10getEnvImplPKc
  Referenced from: libSoapySDR.dylib
  Expected in: flat namespace
```

The problem seems to occur in any combination of Luaradio (**HEAD** x **homebrew**) and `libSoapySDR` (**HEAD** x **homebrew**).

# Proposed Solution

Loading `libSoapySDR` with `pcall(ffi.load, "libSoapySDR", true)` (emphasis on **true**) in both source and sink seems to avoid the problem.

# Version Details

`LuaRadio 0.5.0 - Vanya A. Sergeev. http://luaradio.io`

```
luajit          LuaJIT 2.1.0-beta3
os              OSX
arch            x64
page size       4096
cpu count       4
cpu model       MacBookPro12,1
features
    fftw3f      true
    volk        false
    liquid      false

```

**Comment by JayKickliter** [comment]
I'm running into the same problem.
