### ISSUE TITLE
Travis CI might be outdated. 

### ISSUE THREAD

**Issue by ralfbiedert** [vsergeev/luaradio#46]
When creating a PR for #44 (see #45), Travis CI failed. 

From what I could see in the logs that was due to unrelated issues in the `.travis.yml`.

Although I have trouble accessing the logs again at this point, there were 3rd party download failures on the console IIRC.

**Comment by vsergeev** [comment]
I've updated the dependencies in the Travis CI build config and everything is passing now on devel. After I release v0.6.1, the build on future PRs based on master should be working correctly as well.
