### ISSUE TITLE
throttle block throttles too enthusiastically

### ISSUE THREAD

**Issue by rfc6919** [vsergeev/luaradio#47]
(seen on macOS 10.13 / luajit 2.0.5 and Debian Stretch / luajit 2.0.4, both with luaradio HEAD)

The throttle block loves to throttle, regardless of the sample rate it should be targeting, and looks like it asymptotes towards zero throughput. The following is from a Debian Stretch system:

    russm@thompson:~/luaradio$ ./luaradio --platform
    luajit          LuaJIT 2.0.4
    os              Linux
    arch            x64
    page size       4096
    cpu count       16
    cpu model       Intel(R) Xeon(R) CPU           E5540  @ 2.53GHz
    features
        fftw3f      true
        volk        false
        liquid      true
    russm@thompson:~/luaradio$ cat throttle.lua 
    local radio = require('radio')
    
    radio.CompositeBlock():connect(
      radio.ZeroSource(radio.types.ComplexFloat32, 4000000),
      radio.ThrottleBlock(),
      radio.BenchmarkSink()
    ):run()
    russm@thompson:~/luaradio$ ./luaradio throttle.lua 
    [BenchmarkSink] 2.46 MS/s (19.66 MB/s)
    [BenchmarkSink] 2.23 MS/s (17.80 MB/s)
    [BenchmarkSink] 2.00 MS/s (15.97 MB/s)
    [BenchmarkSink] 1.79 MS/s (14.30 MB/s)
    [BenchmarkSink] 1.63 MS/s (13.05 MB/s)
    ^Crussm@thompson:~/luaradio$

Throughput continues to drop the longer I leave it running. CPU usage is negligible, and if I comment out the throttle block it runs like so:

    russm@thompson:~/luaradio$ ./luaradio throttle.lua 
    [BenchmarkSink] 851.85 MS/s (6.81 GB/s)
    [BenchmarkSink] 822.14 MS/s (6.58 GB/s)
    [BenchmarkSink] 877.96 MS/s (7.02 GB/s)
    [BenchmarkSink] 898.21 MS/s (7.19 GB/s)
    ^Crussm@thompson:~/luaradio$ 

with throughput staying ~860MS/s.

**Comment by vsergeev** [comment]
Thanks for the report. I see it behave like this on my system too. It's definitely a bug I'll look into.
