### ISSUE TITLE
Project roadmap 0.6.0

### ISSUE THREAD

**Issue by wprayudo** [vsergeev/luaradio#48]
seems like this project get idle for a long time :) .. very interesting in TCP features as in 0.6.0 roadmap 
wait for it ..

regards

**Comment by vsergeev** [comment]
I managed to put out a patch release last September, but the project has admittedly experienced a hiatus over the past year. I just released v0.6.0 with new network sources/sinks and numerous other clean ups and improvements. I hope to keep up putting out regular releases with fixes and new features!

**Comment by wprayudo** [comment]
thank you for making this great stuff live again :) 👍
