### ISSUE TITLE
Common place for people to list blocks they have made?

### ISSUE THREAD

**Issue by wgaylord** [vsergeev/luaradio#50]
Is there a common place where people can link to blocks they have created? (To help avoid the one-off make a block for a project and no one else use it because they can't find it)

Because I have been looking around if anyone has made a custom block that allows for retuneing of the SDR during a run. But I havent found one. (The inability to retune on the fly is one of the few reasons I have been stuck with GUNRadio currently)

**Comment by vsergeev** [comment]
For more general blocks, PRs into the main project are encouraged. For more custom blocks, I'll have to think about easy ways of providing a public repository, especially as the project grows and approaches v1.0.0. Any suggestions are of course welcome.
