### ISSUE TITLE
Add identification information to debugging-related sinks

### ISSUE THREAD

**Issue by phrrngtn** [vsergeev/luaradio#61]
HI,
I have been been using a number of debugging sinks to help me learn LuaRadio e.g. PrintSink, BenchmarkSink. However, if one uses more than one of either type in a script and one logs to the screen rather than to a specific file, it does not seem to be possible to figure out which block is generating the output. 

It would be very handy to be able to associate a title with these blocks when they are being instantiated (similar to what is done with, e.g., the GnuPlot sinks. and for this title to appear in the output.

This looks pretty easy to do by extending the signatures of the relevant blocks but I thought I would ask you about it first in case you had any ideas/preferences on how you would like it done (or, indeed, if there is a much better approach)

thanks,
pjjH

**Comment by vsergeev** [comment]
Thanks for the suggestion. I've added support for a custom reporting title to PrintSink and BenchmarkSink in d65be96 and bc7b179, respectively. It's available now in the v0.9.0 release. The reference manual will show the updated usage.
